parameters:
    factfinder.navigation.category_path_field_name: 'CategoryPath'

services:
    _defaults:
        public: false
        autowire: true

    Omikron\FactFinder\Oxid\Subscriber\AfterRequestProcessedEventSubscriber:
        tags: ['kernel.event_subscriber']

    Omikron\FactFinder\Oxid\Subscriber\BeforeHeadersSendEventSubscriber:
        tags: ['kernel.event_subscriber']

    Omikron\FactFinder\Oxid\Export\Field\Category\SourceField:
        class: Omikron\FactFinder\Oxid\Export\Field\Category\SourceField
        public: true
        arguments:
            $categoryPathFieldName: '%factfinder.navigation.category_path_field_name%'

    # Twig Extensions
    Omikron\FactFinder\Oxid\Twig\Extensions\Filters\RecordDataJson:
        tags: [ 'twig.extension' ]
