<?php

$sLangName = 'Deutsch';

$aLang = [
    'charset'                                           => 'UTF-8',
    'SHOP_MODULE_GROUP_ffMain'                          => 'Grundeinstellungen',
    'SHOP_MODULE_ffServerUrl'                           => 'Server-URL',
    'SHOP_MODULE_ffChannel'                             => 'Channel',
    'SHOP_MODULE_ffUsername'                            => 'Benutzername',
    'SHOP_MODULE_ffPassword'                            => 'Passwort',
    'SHOP_MODULE_ffAuthPrefix'                          => 'Authorisierungs-Präfix',
    'SHOP_MODULE_ffAuthPostfix'                         => 'Authorisierungs-Postfix',
    'SHOP_MODULE_GROUP_ffAdvanced'                      => 'Erweiterte Einstellungen',
    'SHOP_MODULE_ffApiVersion'                          => 'API-Version',
    'SHOP_MODULE_ffApiVersion_7.2'                      => '7.2',
    'SHOP_MODULE_ffApiVersion_7.3'                      => '7.3',
    'SHOP_MODULE_ffApiVersion_ng'                       => 'NG',
    'SHOP_MODULE_ffUseUrlParams'                        => 'URL-Parameter benutzen?',
    'SHOP_MODULE_ffAddSearchParams'                     => 'Add search params',
    'SHOP_MODULE_ffDisableSingleHit'                    => 'Disable single hit redirects',
    'SHOP_MODULE_GROUP_ffFeatures'                      => 'Features Settings',
    'SHOP_MODULE_ffUseForCategories'                    => 'Kategorieseiten mit FACT-Finder® rendern?',
    'SHOP_MODULE_ffCampaigns'                           => 'Kampagnen',
    'SHOP_MODULE_ffRecommendations'                     => 'Empfehlungen',
    'SHOP_MODULE_ffSimilarProducts'                     => 'Ähnliche Produkte',
    'SHOP_MODULE_ffPushedProducts'                      => 'Pushed products',
    'SHOP_MODULE_GROUP_ffExport'                        => 'Export-Einstellungen',
    'SHOP_MODULE_ffFtpHost'                             => 'FTP-Host',
    'SHOP_MODULE_ffFtpPort'                             => 'FTP-Port',
    'SHOP_MODULE_ffFtpUser'                             => 'FTP-User',
    'SHOP_MODULE_ffFtpPassword'                         => 'FTP-Password',
    'SHOP_MODULE_ffSSLEnabled'                          => 'SSL aktiv?',
    'SHOP_MODULE_ffAutomaticImport'                     => 'Automatic import of product',
    'SHOP_MODULE_ffAutomaticImportData'                 => 'Import Data',
    'SHOP_MODULE_ffAutomaticImportSuggest'              => 'Import Suggest',
    'SHOP_MODULE_ffAutomaticImportRecommendation'       => 'Import Recommendation',
    'SHOP_MODULE_ffHTTPExportUser'                      => 'Basic Auth user for HTTP export',
    'SHOP_MODULE_ffHTTPExportPassword'                  => 'Basic Auth password for HTTP export',
    'HELP_SHOP_MODULE_ffPushedImportTypes'              => 'Verfügbare Werte: data, suggest',
    'FF_TEST_CONNECTION_SUCCESS'                        => 'Connection has been established successfully',
    'FF_ARTICLE_FEED_EXPORT_SUCCESS'                    => 'Article Feed has been exported succesfully',
    'FF_ARTICLE_FEED_UPLOAD_SUCCESS'                    => 'Article Feed has been uploaded succesfully',
    'FF_ARTICLE_FEED_IMPORT_TRIGGERED'                  => 'Import feed file has been triggered',
];
