<?php

$sLangName = 'Deutsch';

$aLang = [
    'charset'                                     => 'UTF-8',
    'SHOP_MODULE_GROUP_ffMain'                    => 'Grundeinstellungen',
    'SHOP_MODULE_ffServerUrl'                     => 'Server-URL',
    'SHOP_MODULE_ffChannel'                       => 'Channel',
    'SHOP_MODULE_ffUsername'                      => 'Benutzername für den FACT-Finder Import User',
    'SHOP_MODULE_ffPassword'                      => 'Passwort',
    'SHOP_MODULE_ffAuthPrefix'                    => 'Authorisierungs-Präfix',
    'SHOP_MODULE_ffAuthPostfix'                   => 'Authorisierungs-Postfix',
    'SHOP_MODULE_GROUP_ffAdvanced'                => 'Erweiterte Einstellungen',
    'SHOP_MODULE_ffApiVersion'                    => 'API-Version',
    'SHOP_MODULE_ffApiVersion_6.9'                => '6.9',
    'SHOP_MODULE_ffApiVersion_6.10'               => '6.10',
    'SHOP_MODULE_ffApiVersion_6.11'               => '6.11',
    'SHOP_MODULE_ffApiVersion_7.0'                => '7.0',
    'SHOP_MODULE_ffApiVersion_7.1'                => '7.1',
    'SHOP_MODULE_ffApiVersion_7.2'                => '7.2',
    'SHOP_MODULE_ffApiVersion_7.3'                => '7.3',
    'SHOP_MODULE_ffApiVersion_ng'                 => 'NG',
    'SHOP_MODULE_ffUseUrlParams'                  => 'URL-Parameter benutzen?',
    'SHOP_MODULE_ffAddSearchParams'               => 'Zusätzliche Parameter',
    'HELP_SHOP_MODULE_ffAddSearchParams'          => 'Es gibt vier Parameter, die Sie einstellen können:`add-params`, `add-tracking-params`, `keep-url-params`, `parameter-whitelist`. Jede Parameterdefinition sollte in einer separaten Zeile stehen. Beispiel-Verwendung: add-params => customParam1 => value1, customParam2 => value2',
    'SHOP_MODULE_GROUP_ffFeatures'                => 'Features Settings',
    'SHOP_MODULE_ffUseForCategories'              => 'Kategorieseiten mit FACT-Finder® rendern?',
    'SHOP_MODULE_ffCampaigns'                     => 'Kampagnen',
    'SHOP_MODULE_ffRecommendations'               => 'Empfehlungen',
    'SHOP_MODULE_ffSimilarProducts'               => 'Ähnliche Produkte',
    'SHOP_MODULE_ffPushedProducts'                => 'Pushed products',
    'SHOP_MODULE_GROUP_ffFeed'                    => 'Feed-Einstellungen',
    'SHOP_MODULE_ffExportAttributes'              => 'Exportierte Attribute',
    'HELP_SHOP_MODULE_ffExportAttributes'         => 'Wähle die Attribute aus, die du exportieren möchtest. Multi-Attribute werden in einer Spalte gruppiert, und stellen typischerweise Filter dar.',
    'SHOP_MODULE_GROUP_ffExport'                  => 'Export-Einstellungen',
    'SHOP_MODULE_ffFtpHost'                       => 'FTP-Host',
    'SHOP_MODULE_ffFtpPort'                       => 'FTP-Port',
    'SHOP_MODULE_ffFtpUser'                       => 'FTP-User',
    'SHOP_MODULE_ffFtpPassword'                   => 'FTP-Password',
    'SHOP_MODULE_ffSSLEnabled'                    => 'SSL aktiv?',
    'SHOP_MODULE_ffAutomaticImport'               => 'Automatic import of product',
    'SHOP_MODULE_ffAutomaticImportData'           => 'Import Data',
    'SHOP_MODULE_ffAutomaticImportSuggest'        => 'Import Suggest',
    'SHOP_MODULE_ffAutomaticImportRecommendation' => 'Import Recommendation',
    'SHOP_MODULE_ffHTTPExportUser'                => 'Basic Auth user for HTTP export',
    'SHOP_MODULE_ffHTTPExportPassword'            => 'Basic Auth password for HTTP export',
    'HELP_SHOP_MODULE_ffPushedImportTypes'        => 'Verfügbare Werte: data, suggest',
    'FF_TEST_CONNECTION_SUCCESS'                  => 'Connection has been established successfully',
    'FF_ARTICLE_FEED_EXPORT_SUCCESS'              => 'Article Feed has been exported succesfully',
    'FF_ARTICLE_FEED_UPLOAD_SUCCESS'              => 'Article Feed has been uploaded succesfully',
    'FF_ARTICLE_FEED_IMPORT_TRIGGERED'            => 'Import feed file has been triggered',
];
