services:
    Omikron\FactFinder\Oxid\Command\FeedExport:
        class: Omikron\FactFinder\Oxid\Command\FeedExport
        tags:
            - { name: 'console.command', command: 'factfinder:feed-export' }

