<?php

$sLangName = 'English';

$aLang = [
    'charset'                                     => 'UTF-8',
    'SHOP_MODULE_GROUP_ffMain'                    => 'Main settings',
    'SHOP_MODULE_ffServerUrl'                     => 'Server URL',
    'SHOP_MODULE_ffChannel'                       => 'Channel',
    'SHOP_MODULE_ffUsername'                      => 'Username',
    'SHOP_MODULE_ffPassword'                      => 'Password',
    'SHOP_MODULE_ffAuthPrefix'                    => 'Authorization Prefix',
    'SHOP_MODULE_ffAuthPostfix'                   => 'Authorization Postfix',
    'SHOP_MODULE_GROUP_ffAdvanced'                => 'Advanced',
    'SHOP_MODULE_ffApiVersion'                    => 'API Version',
    'SHOP_MODULE_ffApiVersion_6.9'                => '6.9',
    'SHOP_MODULE_ffApiVersion_6.10'               => '6.10',
    'SHOP_MODULE_ffApiVersion_6.11'               => '6.11',
    'SHOP_MODULE_ffApiVersion_7.0'                => '7.0',
    'SHOP_MODULE_ffApiVersion_7.1'                => '7.1',
    'SHOP_MODULE_ffApiVersion_7.2'                => '7.2',
    'SHOP_MODULE_ffApiVersion_7.3'                => '7.3',
    'SHOP_MODULE_ffApiVersion_ng'                 => 'NG',
    'SHOP_MODULE_ffUseUrlParams'                  => 'Use URL params?',
    'SHOP_MODULE_ffAddSearchParams'               => 'Additional parameters',
    'HELP_SHOP_MODULE_ffAddSearchParams'          => 'There are four parameters you can set: `add-params`, `add-tracking-params`, `keep-url-params`, `parameter-whitelist`. Each parameter definition should be placed in separate row. Example usage : add-params => customParam1 => value1, customParam2 => value2',
    'SHOP_MODULE_GROUP_ffFeatures'                => 'Features Settings',
    'SHOP_MODULE_ffUseForCategories'              => 'Use FACT-Finder® for category pages?',
    'SHOP_MODULE_ffCampaigns'                     => 'Campaigns',
    'SHOP_MODULE_ffRecommendations'               => 'Recommendations',
    'SHOP_MODULE_ffSimilarProducts'               => 'Similar products',
    'SHOP_MODULE_ffPushedProducts'                => 'Pushed products',
    'SHOP_MODULE_GROUP_ffExport'                  => 'Export Settings',
    'SHOP_MODULE_ffFtpHost'                       => 'FTP host',
    'SHOP_MODULE_ffFtpPort'                       => 'FTP port',
    'SHOP_MODULE_ffFtpUser'                       => 'FTP user',
    'SHOP_MODULE_ffFtpPassword'                   => 'FTP password',
    'SHOP_MODULE_ffSSLEnabled'                    => 'SSL enabled',
    'SHOP_MODULE_ffAutomaticImport'               => 'Automatic import of product',
    'SHOP_MODULE_ffAutomaticImportData'           => 'Import Data',
    'SHOP_MODULE_ffAutomaticImportSuggest'        => 'Import Suggest',
    'SHOP_MODULE_ffAutomaticImportRecommendation' => 'Import Recommendation',
    'SHOP_MODULE_ffPushedImportTypes'             => 'Pushed import types',
    'SHOP_MODULE_ffHTTPExportUser'                => 'Basic Auth user for HTTP export',
    'SHOP_MODULE_ffHTTPExportPassword'            => 'Basic Auth password for HTTP export',
    'FF_TEST_CONNECTION_SUCCESS'                  => 'Connection has been established successfully',
    'FF_ARTICLE_FEED_EXPORT_SUCCESS'              => 'Article Feed has been exported succesfully',
    'FF_ARTICLE_FEED_UPLOAD_SUCCESS'              => 'Article Feed has been uploaded succesfully',
    'FF_ARTICLE_FEED_IMPORT_TRIGGERED'            => 'Import feed file has been triggered',
];
